/** The exact 20+ regex patterns + messages from the reference app's validation.js — ported 1:1 so behavior matches exactly. */
export const PATTERNS: Record<string, RegExp> = {
  email: /^[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}$/,
  phone: /^(\+91[\s\-]?|0)?[6-9]\d{9}$/,
  password: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*()_+\-=[\]{};':"\\|,.<>/?]).{6,}$/,
  creditCard: /^\d{16}$/,
  cvv: /^\d{3}$/,
  cardExpiry: /^(0[1-9]|1[0-2])\/\d{2}$/,
  upiId: /^[a-zA-Z0-9._\-]+@[a-zA-Z]{2,}$/,
  postalCode: /^\d{6}$/,
  name: /^[a-zA-Z\s]{2,50}$/,
  productName: /^.{3,100}$/,
  sku: /^[A-Z]{2,5}-\d{3,6}$/,
  categoryName: /^.{3,50}$/,
  price: /^\d+(\.\d{1,2})?$/,
  addressLine: /^.{5,200}$/,
  city: /^[a-zA-Z\s]{2,50}$/,
  state: /^[a-zA-Z\s]{2,50}$/,
  brand: /^.{2,50}$/,
  label: /^.{2,30}$/,
};

export const MESSAGES: Record<string, string> = {
  email: 'Enter a valid email address (e.g., user@example.com)',
  phone: 'Enter a valid Indian mobile number (e.g., 9876543210)',
  password: 'Min 6 chars with uppercase, lowercase, digit, and special character',
  creditCard: 'Enter a valid 16-digit card number',
  cvv: 'Enter a valid 3-digit CVV',
  cardExpiry: 'Enter expiry in MM/YY format',
  upiId: 'Enter a valid UPI ID (e.g., name@bank)',
  postalCode: 'Enter a valid 6-digit PIN code',
  name: 'Name must be 2-50 characters (letters and spaces only)',
  productName: 'Product name must be 3-100 characters',
  sku: 'SKU format: XX-000 (e.g., EL-001)',
  categoryName: 'Category name must be 3-50 characters',
  price: 'Enter a valid price (e.g., 999.99)',
  addressLine: 'Address must be 5-200 characters',
  city: 'City must be 2-50 characters (letters only)',
  state: 'State must be 2-50 characters (letters only)',
  brand: 'Brand must be 2-50 characters',
  label: 'Label must be 2-30 characters',
};
